const mockCommonContents = {
  "menus": {
    "header-menu": [
      {
        "id": 288,
        "title": "About Us",
        "url": "https://loremwellnesscare.com/about-us/",
        "parent": "0"
      },
      {
        "id": 21,
        "title": "Services",
        "url": "http://loremwellnesscare.com/#service",
        "parent": "0"
      },
      {
        "id": 599,
        "title": "Behavior Therapy",
        "url": "https://loremwellnesscare.com/services/best-behavior-therapy-center-in-kochi/",
        "parent": "21"
      },
      {
        "id": 418,
        "title": "Speech Therapy",
        "url": "https://loremwellnesscare.com/services/best-speech-therapy-center-in-kochi/",
        "parent": "21"
      },
      {
        "id": 417,
        "title": "Special Education",
        "url": "https://loremwellnesscare.com/services/best-special-education-services-in-kochi/",
        "parent": "21"
      },
      {
        "id": 415,
        "title": "Physiotherapy",
        "url": "https://loremwellnesscare.com/services/best-physiotherapy-services-in-kochi/",
        "parent": "21"
      },
      {
        "id": 412,
        "title": "Occupational Therapy",
        "url": "https://loremwellnesscare.com/services/best-occupational-therapy-in-kochi/",
        "parent": "21"
      },
      {
        "id": 22,
        "title": "Our Team",
        "url": "http://loremwellnesscare.com/about-us/#team",
        "parent": "0"
      },
      {
        "id": 287,
        "title": "Blog",
        "url": "https://loremwellnesscare.com/blog/",
        "parent": "0"
      },
      {
        "id": 289,
        "title": "Contact Us",
        "url": "https://loremwellnesscare.com/contact-us/",
        "parent": "0"
      }
    ],
    "footer-quick-links-menu": [
      {
        "id": 64,
        "title": "Home",
        "url": "https://loremwellnesscare.com/",
        "parent": "0"
      },
      {
        "id": 349,
        "title": "About Us",
        "url": "https://loremwellnesscare.com/about-us/",
        "parent": "0"
      },
      {
        "id": 66,
        "title": "Services",
        "url": "http://loremwellnesscare.com/#service",
        "parent": "0"
      },
      {
        "id": 67,
        "title": "Our Team",
        "url": "http://loremwellnesscare.com/about-us/#team",
        "parent": "0"
      },
      {
        "id": 348,
        "title": "Blog",
        "url": "https://loremwellnesscare.com/blog/",
        "parent": "0"
      },
      {
        "id": 350,
        "title": "Contact Us",
        "url": "https://loremwellnesscare.com/contact-us/",
        "parent": "0"
      }
    ],
    "footer-service-menu1": [
      {
        "id": 351,
        "title": "Best Speech Therapy Center in Kochi",
        "url": "https://loremwellnesscare.com/services/best-speech-therapy-center-in-kochi/",
        "parent": "0"
      },
      {
        "id": 352,
        "title": "Best Special Education Services in Kochi",
        "url": "https://loremwellnesscare.com/services/best-special-education-services-in-kochi/",
        "parent": "0"
      },
      {
        "id": 353,
        "title": "Best Physiotherapy Center in Kochi",
        "url": "https://loremwellnesscare.com/services/best-physiotherapy-services-in-kochi/",
        "parent": "0"
      },
      {
        "id": 355,
        "title": "Best Occupational Therapy in Kochi",
        "url": "https://loremwellnesscare.com/services/best-occupational-therapy-in-kochi/",
        "parent": "0"
      }
    ],
    "footer-service-menu2": []
  },
  "options": {
    "copyright": "Lorem Wellness Care © 2024. All right reserved",
    "footer_appointment_block": {
      "image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/ft-logo.png",
      "heading": "Take the Next Step",
      "content": "Ready to Enhance Your Health and Well-Being?",
      "button_name": "Book an Appointment",
      "button_link": "/contact-us/",
      "phone_number": "+91 9207070711"
    },
    "header_phone": "+91 9207070711",
    "logo": "https://loremwellnesscare.com/wp-content/uploads/2024/08/logo.svg",
    "main_footer": {
      "contact_block": {
        "address": "Plot No G-341 Street B \r\nCross road 10B Panampilly Nagar, Kochi, Kerala 682036",
        "address_location": "https://maps.app.goo.gl/chcV13t1DcX2uMaN7",
        "phone_block": [
          {
            "phone": "+91 484 2929270"
          },
          {
            "phone": "+91 9207070711"
          }
        ],
        "e-mail": "info@loremwellnesscare.com",
        "social_media": [
          {
            "social_icon": "https://loremwellnesscare.com/wp-content/uploads/2024/08/fb.svg",
            "social_url": "https://www.facebook.com/LoremWellnessCare"
          },
          {
            "social_icon": "https://loremwellnesscare.com/wp-content/uploads/2024/08/insta.svg",
            "social_url": "https://www.instagram.com/loremwellnesscare/"
          },
          {
            "social_icon": "https://loremwellnesscare.com/wp-content/uploads/2024/08/youtube.svg",
            "social_url": "https://www.youtube.com/channel/UC9BcwSWbSecr6oqyemtZNVw"
          },
          {
            "social_icon": "https://loremwellnesscare.com/wp-content/uploads/2024/08/linkeden.svg",
            "social_url": "https://in.linkedin.com/company/lorem-wellness-care"
          }
        ],
        "whatsapp_number": "+919207070711"
      }
    },
    "mobile_contact_button": "CONTACT US",
    "mobile_contact_button_link": "#",
    "team_section": {
      "team_members_details": [
        {
          "team_member_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/Nandha-Ganesh-Special-Education.jpg",
          "name": "Nandha Ganesh",
          "positions": "Special-Education"
        },
        {
          "team_member_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/Meghna-PC-Psychologist.jpg",
          "name": "Meghna PC",
          "positions": "Psychologist"
        },
        {
          "team_member_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/Honey-Krishnan-Physiotherapist.jpg",
          "name": "Honey Krishnan",
          "positions": "Physiotherapist"
        },
        {
          "team_member_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/Vismaya-K-P-Speech-Language-Pathologist.jpg",
          "name": "Vismaya KP",
          "positions": "Speech Language Pathologist"
        },
        {
          "team_member_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/Naseeba-Faburikage-Bidaruge-Speech-Language-Pathologist-2.jpg",
          "name": "Naseeba Faburikage Bidaruge",
          "positions": "Speech Language Pathologist"
        }
      ]
    }
  },
  "services": [
    {
      "title": "Best Behavior Therapy Center in Kochi",
      "slug": "best-behavior-therapy-center-in-kochi",
      "acf": {
        "services_list_icon_image": "https://loremwellnesscare.com/wp-content/uploads/2025/01/behavioral.png",
        "services_list_expert_content": "<p>It&#8217;s a form of psychotherapy that mainly aims on behavior</p>\n"
      }
    },
    {
      "title": "Best Speech Therapy Center in Kochi",
      "slug": "best-speech-therapy-center-in-kochi",
      "acf": {
        "services_list_icon_image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/speech.png",
        "services_list_expert_content": "<p>Helping you find your voice.</p>\n"
      }
    },
    {
      "title": "Best Special Education Services in Kochi",
      "slug": "best-special-education-services-in-kochi",
      "acf": {
        "services_list_icon_image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/education.png",
        "services_list_expert_content": "<p>Empowering every child to thrive.</p>\n"
      }
    },
    {
      "title": "Best Physiotherapy Center in Kochi",
      "slug": "best-physiotherapy-services-in-kochi",
      "acf": {
        "services_list_icon_image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/physiotherapy.png",
        "services_list_expert_content": "<p>Restoring movement<br />\nand function.</p>\n"
      }
    },
    {
      "title": "Best Occupational Therapy in Kochi",
      "slug": "best-occupational-therapy-in-kochi",
      "acf": {
        "services_list_icon_image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/occupational.png",
        "services_list_expert_content": "<p>Assisting you in daily living activities.</p>\n"
      }
    }
  ],
  "blogs": [
    {
      "title": "Why Multidisciplinary Therapy is the Future of Rehabilitation in Kochi?",
      "slug": "why-multidisciplinary-therapy-is-the-future-of-rehabilitation-in-kochi",
      "acf": {
        "blog_list_image": "https://loremwellnesscare.com/wp-content/uploads/2025/01/supportive_family_crucial_role.jpg",
        "blog_list_expert_content": "<p>To get to the answer on Why Multidisciplinary Therapy is the future of Rehabilitation, Let us first know What Multidisciplinary Therapy is..</p>\n"
      }
    },
    {
      "title": "How OT, Physiotherapy, and Speech Therapy Work Together for Holistic Recovery",
      "slug": "how-ot-physiotherapy-and-speech-therapy-work-together-for-holistic-recovery",
      "acf": {
        "blog_list_image": "https://loremwellnesscare.com/wp-content/uploads/2025/01/mw2.jpg",
        "blog_list_expert_content": "<p>Lorem Wellness Care, the best Occupational Therapy center in Kochi provides a multidisciplinary approach where Occupational Therapy</p>\n"
      }
    },
    {
      "title": "Convenient OT Services in Kochi: Clinic and Home-Based Options by Lorem Wellness Care",
      "slug": "convenient-ot-services-in-kochi-clinic-and-home-based-options-by-lorem-wellness-care",
      "acf": {
        "blog_list_image": "https://loremwellnesscare.com/wp-content/uploads/2025/01/developing_personalized_support_plans.jpg",
        "blog_list_expert_content": "<p>In this fast moving world finding and getting the right support for your loved ones has become very difficult.</p>\n"
      }
    }
  ]
};

const mockHomeContents = [
  {
    "id": 12,
    "date": "2024-08-05T09:55:04",
    "date_gmt": "2024-08-05T09:55:04",
    "guid": {
      "rendered": "http://loremwellnesscare.com/?page_id=12"
    },
    "modified": "2025-10-30T06:55:59",
    "modified_gmt": "2025-10-30T06:55:59",
    "slug": "home",
    "status": "publish",
    "type": "page",
    "link": "https://loremwellnesscare.com/",
    "title": {
      "rendered": "Home"
    },
    "content": {
      "rendered": "",
      "protected": false
    },
    "excerpt": {
      "rendered": "",
      "protected": false
    },
    "author": 1,
    "featured_media": 431,
    "parent": 0,
    "menu_order": 0,
    "comment_status": "closed",
    "ping_status": "closed",
    "template": "templates/home.php",
    "meta": {
      "_acf_changed": false,
      "footnotes": ""
    },
    "class_list": [
      "post-12",
      "page",
      "type-page",
      "status-publish",
      "has-post-thumbnail",
      "hentry"
    ],
    "acf": {
      "banner_section": {
        "banner_slider": [
          {
            "banner_image": "https://loremwellnesscare.com/wp-content/uploads/2025/10/banner-home.webp",
            "banner_heading": "Helping Your Child Find Ability to Talk Through Speech Therapy",
            "banner_content": "<p>From Frustration to Flourishing: Let Us Help Your Child Communicate Better.</p>\n",
            "button_name_1": "Book an Appointment",
            "button_link_1": "/contact-us/",
            "button_name_2": "Learn More",
            "button_link_2": "/about-us/"
          }
        ]
      },
      "services_section": {
        "main_heading": "A Wide Range of Services to \r\nMeet Your Health Needs"
      },
      "why_choose_us": {
        "why_choose_us__and_review_section": {
          "why_choose_us_block": {
            "main_heading": "Why Choose Us?",
            "button_name": "Book an Appointment",
            "button_link": "/contact-us/",
            "why_choose_us_box": [
              {
                "image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/nine.jpg",
                "heading": "Experienced Professionals",
                "content": "<p>Our team of experts is here to provide top-notch care.</p>\n"
              },
              {
                "image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/ten.jpg",
                "heading": "Personalized Care Plans",
                "content": "<p>Tailored care plans to meet your unique needs.</p>\n"
              },
              {
                "image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/one.jpg",
                "heading": "Comprehensive Service Range",
                "content": "<p>A wide array of services under one roof.</p>\n"
              }
            ]
          },
          "review_block": {
            "review_image": "https://loremwellnesscare.com/wp-content/uploads/2024/08/review.jpg",
            "review_content": "<p>I wanted to take a moment to express my sincere gratitude for the remarkable improvements I&#8217;ve experienced under the care and treatment of Dr. Louis.</p>\n",
            "name": "Bizy Bala",
            "button_name": "Reall all customers reviews",
            "button_link": "https://g.co/kgs/sABJgAQ"
          }
        }
      },
      "about_section": {
        "main_heading": "About Us",
        "content": "<p>Lorem Wellness Care is committed to providing high-quality healthcare services tailored to meet the needs of individuals at every stage of life.</p>\n",
        "timeline_block": [
          {
            "number": "16",
            "data_head": "Years of expertise"
          },
          {
            "number": "11",
            "data_head": "Personnel"
          },
          {
            "number": "70",
            "data_head": "Daily Sessions"
          }
        ]
      },
      "team_section": {
        "button_name": "Get Assistance",
        "button_link": "/about-us/#team"
      },
      "blog_section": {
        "main_heading": "See Latest Articles"
      },
      "gallery_section": {
        "main_heading": "Wake around through our facilities",
        "gallery_slider": [
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/eleven.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/five.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/Four.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/six.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/thirteen.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/three.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/twelve.jpg"
          },
          {
            "gallery_image": "https://loremwellnesscare.com/wp-content/uploads/2024/11/two.jpg"
          }
        ],
        "button_name": "View All",
        "button_link": "#"
      }
    },
    "rankMath": {
      "parentDomain": "loremwellnesscare.com",
      "noFollowDomains": [],
      "noFollowExcludeDomains": [],
      "noFollowExternalLinks": false,
      "featuredImageNotice": "The featured image should be at least 200 by 200 pixels to be picked up by Facebook and other social media sites.",
      "pluginReviewed": false,
      "postSettings": {
        "linkSuggestions": true,
        "useFocusKeyword": false
      },
      "frontEndScore": false,
      "postName": "home",
      "permalinkFormat": "https://loremwellnesscare.com/",
      "showLockModifiedDate": true,
      "assessor": {
        "focusKeywordLink": "https://loremwellnesscare.com/wp-admin/edit.php?focus_keyword=%focus_keyword%&post_type=%post_type%",
        "hasTOCPlugin": false,
        "primaryTaxonomy": false,
        "serpData": {
          "title": "Lorem Wellness Care | Comprehensive Child Development and Rehabilitation Services in Kochi",
          "description": "At Lorem Wellness Care in Kochi, we specialize in child development, women's wellness, mental health care, and rehabilitation for orthopedic and neurological conditions. Our multidisciplinary team offers personalized therapies including speech therapy, physiotherapy, occupational therapy, and special education to enhance your well-being.\n",
          "focusKeywords": "Lorem Wellness Care",
          "pillarContent": false,
          "canonicalUrl": "",
          "breadcrumbTitle": "",
          "advancedRobots": [],
          "facebookTitle": "Best Autism Treatment Center in Kochi | Child Development Centre",
          "facebookDescription": "Lorem Wellness Care is best wellness care center provides treatments for autism, child development, cerebral palsy, parkinsonism diseases, down syndrome, etc. Book a call",
          "facebookImage": "https://loremwellnesscare.com/wp-content/uploads/2024/09/lwc-ogimage-1024x520.jpg",
          "facebookImageID": "431",
          "facebookHasOverlay": false,
          "facebookImageOverlay": "",
          "facebookAuthor": "",
          "twitterCardType": "",
          "twitterUseFacebook": true,
          "twitterTitle": "",
          "twitterDescription": "",
          "twitterImage": "",
          "twitterImageID": "",
          "twitterHasOverlay": false,
          "twitterImageOverlay": "",
          "twitterPlayerUrl": "",
          "twitterPlayerSize": "",
          "twitterPlayerStream": "",
          "twitterPlayerStreamCtype": "",
          "twitterAppDescription": "",
          "twitterAppIphoneName": "",
          "twitterAppIphoneID": "",
          "twitterAppIphoneUrl": "",
          "twitterAppIpadName": "",
          "twitterAppIpadID": "",
          "twitterAppIpadUrl": "",
          "twitterAppGoogleplayName": "",
          "twitterAppGoogleplayID": "",
          "twitterAppGoogleplayUrl": "",
          "twitterAppCountry": "",
          "robots": {
            "index": true
          },
          "twitterAuthor": "username",
          "primaryTerm": 0,
          "authorName": "Admin@Lorem",
          "titleTemplate": "%title% %page% %sep% %sitename%",
          "descriptionTemplate": "",
          "showScoreFrontend": true,
          "lockModifiedDate": false
        },
        "powerWords": [
          "a cut above",
          "absolute",
          "absolutely",
          "absolutely lowest",
          "absurd",
          "abuse",
          "accurate",
          "accuse",
          "achieve",
          "actionable",
          "adaptable",
          "adequate",
          "admit",
          "adorable",
          "advantage",
          "advice",
          "affordable",
          "aggravate",
          "aggressive",
          "agitated",
          "agonizing",
          "agony",
          "alarmed",
          "alarming",
          "alienated",
          "aligned",
          "alive",
          "all-inclusive",
          "alluring",
          "always",
          "amazing",
          "amp",
          "animated",
          "annihilate",
          "announcing",
          "anonymous",
          "antagonistic",
          "anxious",
          "apocalypse",
          "appalled",
          "approved",
          "approving",
          "argumentative",
          "armageddon",
          "arrogant",
          "ass kicking",
          "assault",
          "assured",
          "astonishing",
          "astounded",
          "astounding",
          "at ease",
          "atrocious",
          "attack",
          "attractive",
          "audacity",
          "authentic",
          "authoritative",
          "authority",
          "avoid",
          "aware",
          "awe-inspiring",
          "awesome",
          "awkward",
          "backbone",
          "backdoor",
          "backed",
          "backlash",
          "backstabbing",
          "badass",
          "balanced",
          "banned",
          "bargain",
          "barrage",
          "basic",
          "battle",
          "beaming",
          "beat down",
          "beating",
          "beautiful",
          "beauty",
          "begging",
          "behind the scenes",
          "belief",
          "belong",
          "best",
          "best-selling",
          "better",
          "beware",
          "big",
          "billion",
          "black market",
          "blacklisted",
          "blast",
          "blessed",
          "blinded",
          "blissful",
          "blood",
          "bloodbath",
          "bloodcurdling",
          "bloody",
          "blunder",
          "blushing",
          "bold",
          "bomb",
          "bona",
          "bona fide",
          "bonanza",
          "bonus",
          "bootleg",
          "bottom line",
          "bountiful",
          "brave",
          "bravery",
          "brazen",
          "break",
          "breaking",
          "breakthrough",
          "breathtaking",
          "bright",
          "brilliant",
          "broke",
          "brutal",
          "budget",
          "buffoon",
          "bullshit",
          "bully",
          "bumbling",
          "buy",
          "cadaver",
          "calm",
          "cancel anytime",
          "capable",
          "captivate",
          "captivating",
          "carefree",
          "case study",
          "cash",
          "cataclysmic",
          "catapult",
          "catastrophe",
          "caution",
          "censored",
          "centered",
          "certain",
          "certainly",
          "certified",
          "challenge",
          "charming",
          "cheap",
          "cheat",
          "cheat-sheet",
          "cheer",
          "cheerful",
          "child-like",
          "clarity",
          "classified",
          "clear",
          "clueless",
          "collapse",
          "colorful",
          "colossal",
          "comfortable",
          "compare",
          "competitive",
          "complete",
          "completely",
          "completeness",
          "comprehensive",
          "compromise",
          "compulsive",
          "concealed",
          "conclusive",
          "condemning",
          "condescending",
          "confess",
          "confession",
          "confessions",
          "confident",
          "confidential",
          "conquer",
          "conscientious",
          "constructive",
          "content",
          "contrary",
          "controlling",
          "controversial",
          "convenient",
          "convert",
          "cool",
          "cooperative",
          "copy",
          "corpse",
          "corrupt",
          "corrupting",
          "courage",
          "courageous",
          "cover-up",
          "covert",
          "coward",
          "cowardly",
          "crammed",
          "crave",
          "crazy",
          "create",
          "creative",
          "cringeworthy",
          "cripple",
          "crisis",
          "critical",
          "crooked",
          "crush",
          "crushing",
          "damaging",
          "danger",
          "dangerous",
          "daring",
          "dazzling",
          "dead",
          "deadline",
          "deadly",
          "death",
          "decadent",
          "deceived",
          "deceptive",
          "deep",
          "defiance",
          "definitely",
          "definitive",
          "defying",
          "dejected",
          "delicious",
          "delight",
          "delighted",
          "delightful",
          "delirious",
          "delivered",
          "demoralizing",
          "deplorable",
          "depraved",
          "desire",
          "desperate",
          "despicable",
          "destiny",
          "destroy",
          "detailed",
          "devastating",
          "devoted",
          "diagnosed",
          "direct",
          "dirty",
          "disadvantages",
          "disastrous",
          "discount",
          "discover",
          "disdainful",
          "disempowered",
          "disgusted",
          "disgusting",
          "dishonest",
          "disillusioned",
          "disoriented",
          "distracted",
          "distraught",
          "distressed",
          "distrustful",
          "divulge",
          "document",
          "dollar",
          "dominate",
          "doomed",
          "double",
          "doubtful",
          "download",
          "dreadful",
          "dreamy",
          "drive",
          "drowning",
          "dumb",
          "dynamic",
          "eager",
          "earnest",
          "easily",
          "easy",
          "economical",
          "ecstatic",
          "edge",
          "effective",
          "efficient",
          "effortless",
          "elated",
          "eliminate",
          "elite",
          "embarrass",
          "embarrassed",
          "embarrassing",
          "emergency",
          "emerging",
          "emphasize",
          "empowered",
          "enchant",
          "encouraged",
          "endorsed",
          "energetic",
          "energy",
          "enormous",
          "enraged",
          "enthusiastic",
          "envy",
          "epic",
          "epidemic",
          "essential",
          "ethical",
          "euphoric",
          "evil",
          "exactly",
          "exasperated",
          "excellent",
          "excited",
          "excitement",
          "exciting",
          "exclusive",
          "exclusivity",
          "excruciating",
          "exhilarated",
          "expensive",
          "expert",
          "explode",
          "exploit",
          "explosive",
          "exposed",
          "exquisite",
          "extra",
          "extraordinary",
          "extremely",
          "exuberant",
          "eye-opening",
          "fail",
          "fail-proof",
          "failure",
          "faith",
          "famous",
          "fantasy",
          "fascinating",
          "fatigued",
          "faux",
          "faux pas",
          "fearless",
          "feast",
          "feeble",
          "festive",
          "fide",
          "fierce",
          "fight",
          "final",
          "fine",
          "fired",
          "first",
          "first ever",
          "flirt",
          "fluid",
          "focus",
          "focused",
          "fool",
          "fooled",
          "foolish",
          "forbidden",
          "force-fed",
          "forever",
          "forgiving",
          "forgotten",
          "formula",
          "fortune",
          "foul",
          "frantic",
          "free",
          "freebie",
          "freedom",
          "frenzied",
          "frenzy",
          "frightening",
          "frisky",
          "frugal",
          "frustrated",
          "fulfill",
          "fulfilled",
          "full",
          "fully",
          "fun",
          "fun-loving",
          "fundamentals",
          "funniest",
          "funny",
          "furious",
          "gambling",
          "gargantuan",
          "genius",
          "genuine",
          "gift",
          "gigantic",
          "giveaway",
          "glamorous",
          "gleeful",
          "glorious",
          "glowing",
          "goddamn",
          "gorgeous",
          "graceful",
          "grateful",
          "gratified",
          "gravity",
          "great",
          "greatest",
          "greatness",
          "greed",
          "greedy",
          "gripping",
          "grit",
          "grounded",
          "growth",
          "guaranteed",
          "guilt",
          "guilt-free",
          "gullible",
          "guts",
          "hack",
          "happiness",
          "happy",
          "harmful",
          "harsh",
          "hate",
          "have you heard",
          "havoc",
          "hazardous",
          "healthy",
          "heart",
          "heartbreaking",
          "heartwarming",
          "heavenly",
          "hell",
          "helpful",
          "helplessness",
          "hero",
          "hesitant",
          "hidden",
          "high tech",
          "highest",
          "highly effective",
          "hilarious",
          "hoak",
          "hoax",
          "honest",
          "honored",
          "hope",
          "hopeful",
          "horribly",
          "horrific",
          "horrifying",
          "horror",
          "hostile",
          "how to",
          "huge",
          "humility",
          "humor",
          "hurricane",
          "hurry",
          "hypnotic",
          "idiot",
          "ignite",
          "illegal",
          "illusive",
          "imagination",
          "immediately",
          "imminently",
          "impatience",
          "impatient",
          "impenetrable",
          "important",
          "impressive",
          "improved",
          "in the zone",
          "incapable",
          "incapacitated",
          "incompetent",
          "inconsiderate",
          "increase",
          "incredible",
          "indecisive",
          "indulgence",
          "indulgent",
          "inexpensive",
          "inferior",
          "informative",
          "infuriated",
          "ingredients",
          "innocent",
          "innovative",
          "insane",
          "insecure",
          "insider",
          "insidious",
          "inspired",
          "inspiring",
          "instant savings",
          "instantly",
          "instructive",
          "insult",
          "intel",
          "intelligent",
          "intense",
          "interesting",
          "intriguing",
          "introducing",
          "invasion",
          "investment",
          "iron-clad",
          "ironclad",
          "irresistible",
          "irs",
          "is here",
          "jackpot",
          "jail",
          "jaw-dropping",
          "jealous",
          "jeopardy",
          "jittery",
          "jovial",
          "joyous",
          "jubilant",
          "judgmental",
          "jumpstart",
          "just arrived",
          "keen",
          "kickass",
          "kickstart",
          "kill",
          "killed",
          "killing",
          "kills",
          "know it all",
          "lame",
          "largest",
          "lascivious",
          "last",
          "last chance",
          "last minute",
          "latest",
          "laugh",
          "laughing",
          "launch",
          "launching",
          "lavishly",
          "lawsuit",
          "lazy",
          "left behind",
          "legendary",
          "legitimate",
          "liberal",
          "liberated",
          "lick",
          "lies",
          "life-changing",
          "lifetime",
          "light",
          "lighthearted",
          "likely",
          "limited",
          "literally",
          "little-known",
          "loathsome",
          "lonely",
          "looming",
          "loser",
          "lost",
          "love",
          "lucrative",
          "lunatic",
          "lurking",
          "lust",
          "luxurious",
          "luxury",
          "lying",
          "magic",
          "magical",
          "magnificent",
          "mainstream",
          "malicious",
          "mammoth",
          "manipulative",
          "marked down",
          "massive",
          "master",
          "masterclass",
          "maul",
          "mediocre",
          "meditative",
          "meltdown",
          "memorability",
          "memorable",
          "menacing",
          "mesmerizing",
          "meticulous",
          "mind-blowing",
          "minimalist",
          "miracle",
          "mired",
          "mischievous",
          "misgiving",
          "missing out",
          "mistake",
          "monetize",
          "money",
          "moneyback",
          "moneygrubbing",
          "monumental",
          "most important",
          "motivated",
          "mouth-watering",
          "murder",
          "mystery",
          "nail",
          "naked",
          "natural",
          "naughty",
          "nazi",
          "nest egg",
          "never",
          "new",
          "nightmare",
          "no good",
          "no obligation",
          "no one talks about",
          "no questions asked",
          "no risk",
          "no strings attached",
          "non-controlling",
          "noted",
          "novelty",
          "now",
          "obnoxious",
          "obsessed",
          "obsession",
          "obvious",
          "odd",
          "off-kilter",
          "off-limits",
          "off-the record",
          "offensive",
          "official",
          "okay",
          "on-demand",
          "open-minded",
          "opportunities",
          "optimistic",
          "ordeal",
          "outlawed",
          "outrageousness",
          "outstanding",
          "overcome",
          "overjoyed",
          "overnight",
          "overwhelmed",
          "packed",
          "painful",
          "painless",
          "painstaking",
          "pale",
          "panic",
          "panicked",
          "paralyzed",
          "pas",
          "passionate",
          "pathetic",
          "pay zero",
          "payback",
          "perfect",
          "peril",
          "perplexed",
          "perspective",
          "pessimistic",
          "pioneering",
          "piranha",
          "pitfall",
          "pitiful",
          "placid",
          "plague",
          "played",
          "playful",
          "pleased",
          "pluck",
          "plummet",
          "plunge",
          "poison",
          "poisonous",
          "polarizing",
          "poor",
          "popular",
          "portfolio",
          "pound",
          "powerful",
          "powerless",
          "practical",
          "preposterous",
          "prestige",
          "price",
          "priceless",
          "pride",
          "prison",
          "privacy",
          "private",
          "privileged",
          "prize",
          "problem",
          "productive",
          "professional",
          "profit",
          "profitable",
          "profound",
          "promiscuous",
          "promising",
          "promote",
          "protect",
          "protected",
          "proven",
          "provocative",
          "provoke",
          "psychological",
          "pummel",
          "punch",
          "punish",
          "pus",
          "quadruple",
          "quality",
          "quarrelsome",
          "quick",
          "quick-start",
          "quickly",
          "quiet",
          "radiant",
          "rare",
          "ravenous",
          "rebellious",
          "recession-proof",
          "reckoning",
          "recognized",
          "recommend",
          "recreate",
          "reduced",
          "reflective",
          "refugee",
          "refund",
          "refundable",
          "reject",
          "relaxed",
          "release",
          "relentless",
          "reliable",
          "remarkable",
          "replicate",
          "report",
          "reprimanding",
          "repulsed",
          "repulsive",
          "research",
          "resentful",
          "resourceful",
          "responsible",
          "responsive",
          "rested",
          "restricted",
          "results",
          "retaliating",
          "reveal",
          "revealing",
          "revenge",
          "revengeful",
          "revisited",
          "revolting",
          "revolutionary",
          "reward",
          "rich",
          "ridiculous",
          "risky",
          "riveting",
          "rookie",
          "rowdy",
          "ruin",
          "rules",
          "ruthless",
          "sabotaging",
          "sacred",
          "sadistic",
          "sadly",
          "sadness",
          "safe",
          "safety",
          "sale",
          "sampler",
          "sarcastic",
          "satisfied",
          "savage",
          "savagery",
          "save",
          "savings",
          "savvy",
          "scam",
          "scandal",
          "scandalous",
          "scarce",
          "scared",
          "scary",
          "scornful",
          "scream",
          "searing",
          "secret",
          "secret agenda",
          "secret plot",
          "secrets",
          "secure",
          "security",
          "seductive",
          "seething",
          "seize",
          "selected",
          "self-hating",
          "self-sufficient",
          "sensational",
          "senseless",
          "sensual",
          "serene",
          "seriously",
          "severe",
          "sex",
          "sexy",
          "shaking",
          "shameful",
          "shameless",
          "shaming",
          "shatter",
          "shellacking",
          "shocking",
          "should",
          "shrewd",
          "sick and tired",
          "signs",
          "silly",
          "simple",
          "simplicity",
          "simplified",
          "simplistic",
          "sincere",
          "sinful",
          "sins",
          "six-figure",
          "sizable",
          "sizzle",
          "sizzled",
          "sizzles",
          "sizzling",
          "sizzlingly",
          "skill",
          "skyrocket",
          "slaughter",
          "slave",
          "sleazy",
          "sleeping",
          "sly",
          "smash",
          "smiling",
          "smug",
          "smuggle",
          "smuggled",
          "sneak-peek",
          "sneaky",
          "sniveling",
          "snob",
          "snooty",
          "snotty",
          "soar",
          "soaring",
          "solid",
          "solution",
          "spank",
          "special",
          "spectacular",
          "speedy",
          "spell-binding",
          "spine",
          "spirit",
          "spirited",
          "spiteful",
          "spoiler",
          "spontaneous",
          "spotlight",
          "spunky",
          "squirming",
          "stable",
          "staggering",
          "startling",
          "steady",
          "steal",
          "stealthy",
          "steamy",
          "step-by-step",
          "still",
          "stoic",
          "stop",
          "strange",
          "strangle",
          "strategy",
          "stressed",
          "strong",
          "strongly suggest",
          "struggle",
          "stuck up",
          "studies",
          "stunning",
          "stupid",
          "stupid-simple",
          "sturdy",
          "sublime",
          "succeed",
          "success",
          "successful",
          "suck",
          "suddenly",
          "suffer",
          "sunny",
          "super",
          "super-human",
          "superb",
          "supercharge",
          "superior",
          "supported",
          "supportive",
          "sure",
          "sure fire",
          "surefire",
          "surge",
          "surging",
          "surprise",
          "surprised",
          "surprising",
          "survival",
          "survive",
          "suspicious",
          "sweaty",
          "swoon",
          "swoon-worthy",
          "tailspin",
          "tank",
          "tantalizing",
          "targeted",
          "tawdry",
          "tease",
          "technology",
          "teetering",
          "tempting",
          "tenacious",
          "tense",
          "terrible",
          "terrific",
          "terrified",
          "terrifying",
          "terror",
          "terrorist",
          "tested",
          "thankful",
          "the truth",
          "threaten",
          "threatened",
          "thrilled",
          "thrilling",
          "thug",
          "ticked off",
          "tickled",
          "timely",
          "today",
          "torture",
          "toxic",
          "track record",
          "trade secret",
          "tragedy",
          "tragic",
          "transform",
          "transparency",
          "trap",
          "trapped",
          "trauma",
          "traumatized",
          "treacherous",
          "treasure",
          "tremendous",
          "trend",
          "tricks",
          "triggers",
          "triple",
          "triumph",
          "truly",
          "trusting",
          "trustworthy",
          "truth",
          "truthful",
          "turbo-charge",
          "turbocharges",
          "tweaks",
          "twitching",
          "ultimate",
          "unadulterated",
          "unassuming",
          "unauthorized",
          "unbelievable",
          "unburdened",
          "uncaring",
          "uncensored",
          "uncertain",
          "uncomfortable",
          "unconditional",
          "uncontrollable",
          "unconventional",
          "uncovered",
          "undeniable",
          "under priced",
          "undercover",
          "underground",
          "underhanded",
          "underused",
          "unexpected",
          "unforgettable",
          "unheard of",
          "unhurried",
          "uninterested",
          "unique",
          "unjustified",
          "unknowingly",
          "unleashed",
          "unlimited",
          "unlock",
          "unparalleled",
          "unpopular",
          "unreliable",
          "unresponsive",
          "unseen",
          "unstable",
          "unstoppable",
          "unsure",
          "unsurpassed",
          "untapped",
          "unusual",
          "up-sell",
          "upbeat",
          "uplifted",
          "uplifting",
          "urge",
          "urgent",
          "useful",
          "useless",
          "validate",
          "valor",
          "valuable",
          "value",
          "vanquish",
          "vaporize",
          "venomous",
          "verify",
          "vibrant",
          "vicious",
          "victim",
          "victory",
          "vigorous",
          "vilified",
          "vindictive",
          "violated",
          "violent",
          "volatile",
          "vulnerable",
          "waiting",
          "wanted",
          "wanton",
          "warning",
          "waste",
          "weak",
          "wealth",
          "weird",
          "what no one tells you",
          "whip",
          "whopping",
          "wicked",
          "wild",
          "willpower",
          "withheld",
          "wonderful",
          "wondrous",
          "woozy",
          "world",
          "worry",
          "worst",
          "worthwhile",
          "wounded",
          "wreaking",
          "youthful",
          "zen",
          "zinger"
        ],
        "researchesTests": [
          "contentHasTOC",
          "contentHasShortParagraphs",
          "contentHasAssets",
          "keywordInTitle",
          "keywordInMetaDescription",
          "keywordInPermalink",
          "keywordIn10Percent",
          "keywordInContent",
          "keywordInSubheadings",
          "keywordInImageAlt",
          "keywordDensity",
          "keywordNotUsed",
          "lengthContent",
          "lengthPermalink",
          "linksHasInternal",
          "linksHasExternals",
          "linksNotAllExternals",
          "titleStartWithKeyword",
          "titleSentiment",
          "titleHasPowerWords",
          "titleHasNumber",
          "hasContentAI"
        ],
        "hasRedirection": true,
        "hasBreadcrumb": true
      },
      "homeUrl": "https://loremwellnesscare.com",
      "objectID": 12,
      "objectType": "post",
      "locale": "en",
      "localeFull": "en_US",
      "overlayImages": {
        "play": {
          "name": "Play icon",
          "url": "https://loremwellnesscare.com/wp-content/plugins/seo-by-rank-math/assets/admin/img/icon-play.png",
          "path": "/home/tdos7hpx8tlk/public_html/wp-content/plugins/seo-by-rank-math/assets/admin/img/icon-play.png",
          "position": "middle_center"
        },
        "gif": {
          "name": "GIF icon",
          "url": "https://loremwellnesscare.com/wp-content/plugins/seo-by-rank-math/assets/admin/img/icon-gif.png",
          "path": "/home/tdos7hpx8tlk/public_html/wp-content/plugins/seo-by-rank-math/assets/admin/img/icon-gif.png",
          "position": "middle_center"
        }
      },
      "defautOgImage": "https://loremwellnesscare.com/wp-content/plugins/seo-by-rank-math/assets/admin/img/social-placeholder.jpg",
      "customPermalinks": true,
      "isUserRegistered": false,
      "autoSuggestKeywords": false,
      "connectSiteUrl": "https://rankmath.com/auth?site=https%3A%2F%2Floremwellnesscare.com&r=https%3A%2F%2Floremwellnesscare.com%2Fwp-json%2Fwp%2Fv2%2Fpages%3Fslug%3Dhome%26nonce%3D1ef0186b4b",
      "maxTags": 5,
      "trendsIcon": "<svg viewBox=\"0 0 610 610\"><path d=\"M18.85,446,174.32,290.48l58.08,58.08L76.93,504a14.54,14.54,0,0,1-20.55,0L18.83,466.48a14.54,14.54,0,0,1,0-20.55Z\" style=\"fill:#4285f4\"/><path d=\"M242.65,242.66,377.59,377.6l-47.75,47.75a14.54,14.54,0,0,1-20.55,0L174.37,290.43l47.75-47.75A14.52,14.52,0,0,1,242.65,242.66Z\" style=\"fill:#ea4335\"/><polygon points=\"319.53 319.53 479.26 159.8 537.34 217.88 377.61 377.62 319.53 319.53\" style=\"fill:#fabb05\"/><path d=\"M594.26,262.73V118.61h0a16.94,16.94,0,0,0-16.94-16.94H433.2a16.94,16.94,0,0,0-12,28.92L565.34,274.71h0a16.94,16.94,0,0,0,28.92-12Z\" style=\"fill:#34a853\"/><rect width=\"610\" height=\"610\" style=\"fill:none\"/></svg>",
      "showScore": true,
      "siteFavIcon": "https://loremwellnesscare.com/wp-content/uploads/2024/08/ft-logo.png",
      "canUser": {
        "general": false,
        "advanced": false,
        "snippet": false,
        "social": false,
        "analysis": false,
        "analytics": false,
        "content_ai": false
      },
      "isPro": false,
      "is_front_page": false,
      "trendsUpgradeLink": "https://rankmath.com/pricing/?utm_source=Plugin&utm_medium=CE%20General%20Tab%20Trends&utm_campaign=WP",
      "trendsUpgradeLabel": "Upgrade",
      "trendsPreviewImage": "https://loremwellnesscare.com/wp-content/plugins/seo-by-rank-math/assets/admin/img/trends-preview.jpg",
      "currentEditor": false,
      "homepageData": {
        "assessor": {
          "powerWords": [
            "a cut above",
            "absolute",
            "absolutely",
            "absolutely lowest",
            "absurd",
            "abuse",
            "accurate",
            "accuse",
            "achieve",
            "actionable",
            "adaptable",
            "adequate",
            "admit",
            "adorable",
            "advantage",
            "advice",
            "affordable",
            "aggravate",
            "aggressive",
            "agitated",
            "agonizing",
            "agony",
            "alarmed",
            "alarming",
            "alienated",
            "aligned",
            "alive",
            "all-inclusive",
            "alluring",
            "always",
            "amazing",
            "amp",
            "animated",
            "annihilate",
            "announcing",
            "anonymous",
            "antagonistic",
            "anxious",
            "apocalypse",
            "appalled",
            "approved",
            "approving",
            "argumentative",
            "armageddon",
            "arrogant",
            "ass kicking",
            "assault",
            "assured",
            "astonishing",
            "astounded",
            "astounding",
            "at ease",
            "atrocious",
            "attack",
            "attractive",
            "audacity",
            "authentic",
            "authoritative",
            "authority",
            "avoid",
            "aware",
            "awe-inspiring",
            "awesome",
            "awkward",
            "backbone",
            "backdoor",
            "backed",
            "backlash",
            "backstabbing",
            "badass",
            "balanced",
            "banned",
            "bargain",
            "barrage",
            "basic",
            "battle",
            "beaming",
            "beat down",
            "beating",
            "beautiful",
            "beauty",
            "begging",
            "behind the scenes",
            "belief",
            "belong",
            "best",
            "best-selling",
            "better",
            "beware",
            "big",
            "billion",
            "black market",
            "blacklisted",
            "blast",
            "blessed",
            "blinded",
            "blissful",
            "blood",
            "bloodbath",
            "bloodcurdling",
            "bloody",
            "blunder",
            "blushing",
            "bold",
            "bomb",
            "bona",
            "bona fide",
            "bonanza",
            "bonus",
            "bootleg",
            "bottom line",
            "bountiful",
            "brave",
            "bravery",
            "brazen",
            "break",
            "breaking",
            "breakthrough",
            "breathtaking",
            "bright",
            "brilliant",
            "broke",
            "brutal",
            "budget",
            "buffoon",
            "bullshit",
            "bully",
            "bumbling",
            "buy",
            "cadaver",
            "calm",
            "cancel anytime",
            "capable",
            "captivate",
            "captivating",
            "carefree",
            "case study",
            "cash",
            "cataclysmic",
            "catapult",
            "catastrophe",
            "caution",
            "censored",
            "centered",
            "certain",
            "certainly",
            "certified",
            "challenge",
            "charming",
            "cheap",
            "cheat",
            "cheat-sheet",
            "cheer",
            "cheerful",
            "child-like",
            "clarity",
            "classified",
            "clear",
            "clueless",
            "collapse",
            "colorful",
            "colossal",
            "comfortable",
            "compare",
            "competitive",
            "complete",
            "completely",
            "completeness",
            "comprehensive",
            "compromise",
            "compulsive",
            "concealed",
            "conclusive",
            "condemning",
            "condescending",
            "confess",
            "confession",
            "confessions",
            "confident",
            "confidential",
            "conquer",
            "conscientious",
            "constructive",
            "content",
            "contrary",
            "controlling",
            "controversial",
            "convenient",
            "convert",
            "cool",
            "cooperative",
            "copy",
            "corpse",
            "corrupt",
            "corrupting",
            "courage",
            "courageous",
            "cover-up",
            "covert",
            "coward",
            "cowardly",
            "crammed",
            "crave",
            "crazy",
            "create",
            "creative",
            "cringeworthy",
            "cripple",
            "crisis",
            "critical",
            "crooked",
            "crush",
            "crushing",
            "damaging",
            "danger",
            "dangerous",
            "daring",
            "dazzling",
            "dead",
            "deadline",
            "deadly",
            "death",
            "decadent",
            "deceived",
            "deceptive",
            "deep",
            "defiance",
            "definitely",
            "definitive",
            "defying",
            "dejected",
            "delicious",
            "delight",
            "delighted",
            "delightful",
            "delirious",
            "delivered",
            "demoralizing",
            "deplorable",
            "depraved",
            "desire",
            "desperate",
            "despicable",
            "destiny",
            "destroy",
            "detailed",
            "devastating",
            "devoted",
            "diagnosed",
            "direct",
            "dirty",
            "disadvantages",
            "disastrous",
            "discount",
            "discover",
            "disdainful",
            "disempowered",
            "disgusted",
            "disgusting",
            "dishonest",
            "disillusioned",
            "disoriented",
            "distracted",
            "distraught",
            "distressed",
            "distrustful",
            "divulge",
            "document",
            "dollar",
            "dominate",
            "doomed",
            "double",
            "doubtful",
            "download",
            "dreadful",
            "dreamy",
            "drive",
            "drowning",
            "dumb",
            "dynamic",
            "eager",
            "earnest",
            "easily",
            "easy",
            "economical",
            "ecstatic",
            "edge",
            "effective",
            "efficient",
            "effortless",
            "elated",
            "eliminate",
            "elite",
            "embarrass",
            "embarrassed",
            "embarrassing",
            "emergency",
            "emerging",
            "emphasize",
            "empowered",
            "enchant",
            "encouraged",
            "endorsed",
            "energetic",
            "energy",
            "enormous",
            "enraged",
            "enthusiastic",
            "envy",
            "epic",
            "epidemic",
            "essential",
            "ethical",
            "euphoric",
            "evil",
            "exactly",
            "exasperated",
            "excellent",
            "excited",
            "excitement",
            "exciting",
            "exclusive",
            "exclusivity",
            "excruciating",
            "exhilarated",
            "expensive",
            "expert",
            "explode",
            "exploit",
            "explosive",
            "exposed",
            "exquisite",
            "extra",
            "extraordinary",
            "extremely",
            "exuberant",
            "eye-opening",
            "fail",
            "fail-proof",
            "failure",
            "faith",
            "famous",
            "fantasy",
            "fascinating",
            "fatigued",
            "faux",
            "faux pas",
            "fearless",
            "feast",
            "feeble",
            "festive",
            "fide",
            "fierce",
            "fight",
            "final",
            "fine",
            "fired",
            "first",
            "first ever",
            "flirt",
            "fluid",
            "focus",
            "focused",
            "fool",
            "fooled",
            "foolish",
            "forbidden",
            "force-fed",
            "forever",
            "forgiving",
            "forgotten",
            "formula",
            "fortune",
            "foul",
            "frantic",
            "free",
            "freebie",
            "freedom",
            "frenzied",
            "frenzy",
            "frightening",
            "frisky",
            "frugal",
            "frustrated",
            "fulfill",
            "fulfilled",
            "full",
            "fully",
            "fun",
            "fun-loving",
            "fundamentals",
            "funniest",
            "funny",
            "furious",
            "gambling",
            "gargantuan",
            "genius",
            "genuine",
            "gift",
            "gigantic",
            "giveaway",
            "glamorous",
            "gleeful",
            "glorious",
            "glowing",
            "goddamn",
            "gorgeous",
            "graceful",
            "grateful",
            "gratified",
            "gravity",
            "great",
            "greatest",
            "greatness",
            "greed",
            "greedy",
            "gripping",
            "grit",
            "grounded",
            "growth",
            "guaranteed",
            "guilt",
            "guilt-free",
            "gullible",
            "guts",
            "hack",
            "happiness",
            "happy",
            "harmful",
            "harsh",
            "hate",
            "have you heard",
            "havoc",
            "hazardous",
            "healthy",
            "heart",
            "heartbreaking",
            "heartwarming",
            "heavenly",
            "hell",
            "helpful",
            "helplessness",
            "hero",
            "hesitant",
            "hidden",
            "high tech",
            "highest",
            "highly effective",
            "hilarious",
            "hoak",
            "hoax",
            "honest",
            "honored",
            "hope",
            "hopeful",
            "horribly",
            "horrific",
            "horrifying",
            "horror",
            "hostile",
            "how to",
            "huge",
            "humility",
            "humor",
            "hurricane",
            "hurry",
            "hypnotic",
            "idiot",
            "ignite",
            "illegal",
            "illusive",
            "imagination",
            "immediately",
            "imminently",
            "impatience",
            "impatient",
            "impenetrable",
            "important",
            "impressive",
            "improved",
            "in the zone",
            "incapable",
            "incapacitated",
            "incompetent",
            "inconsiderate",
            "increase",
            "incredible",
            "indecisive",
            "indulgence",
            "indulgent",
            "inexpensive",
            "inferior",
            "informative",
            "infuriated",
            "ingredients",
            "innocent",
            "innovative",
            "insane",
            "insecure",
            "insider",
            "insidious",
            "inspired",
            "inspiring",
            "instant savings",
            "instantly",
            "instructive",
            "insult",
            "intel",
            "intelligent",
            "intense",
            "interesting",
            "intriguing",
            "introducing",
            "invasion",
            "investment",
            "iron-clad",
            "ironclad",
            "irresistible",
            "irs",
            "is here",
            "jackpot",
            "jail",
            "jaw-dropping",
            "jealous",
            "jeopardy",
            "jittery",
            "jovial",
            "joyous",
            "jubilant",
            "judgmental",
            "jumpstart",
            "just arrived",
            "keen",
            "kickass",
            "kickstart",
            "kill",
            "killed",
            "killing",
            "kills",
            "know it all",
            "lame",
            "largest",
            "lascivious",
            "last",
            "last chance",
            "last minute",
            "latest",
            "laugh",
            "laughing",
            "launch",
            "launching",
            "lavishly",
            "lawsuit",
            "lazy",
            "left behind",
            "legendary",
            "legitimate",
            "liberal",
            "liberated",
            "lick",
            "lies",
            "life-changing",
            "lifetime",
            "light",
            "lighthearted",
            "likely",
            "limited",
            "literally",
            "little-known",
            "loathsome",
            "lonely",
            "looming",
            "loser",
            "lost",
            "love",
            "lucrative",
            "lunatic",
            "lurking",
            "lust",
            "luxurious",
            "luxury",
            "lying",
            "magic",
            "magical",
            "magnificent",
            "mainstream",
            "malicious",
            "mammoth",
            "manipulative",
            "marked down",
            "massive",
            "master",
            "masterclass",
            "maul",
            "mediocre",
            "meditative",
            "meltdown",
            "memorability",
            "memorable",
            "menacing",
            "mesmerizing",
            "meticulous",
            "mind-blowing",
            "minimalist",
            "miracle",
            "mired",
            "mischievous",
            "misgiving",
            "missing out",
            "mistake",
            "monetize",
            "money",
            "moneyback",
            "moneygrubbing",
            "monumental",
            "most important",
            "motivated",
            "mouth-watering",
            "murder",
            "mystery",
            "nail",
            "naked",
            "natural",
            "naughty",
            "nazi",
            "nest egg",
            "never",
            "new",
            "nightmare",
            "no good",
            "no obligation",
            "no one talks about",
            "no questions asked",
            "no risk",
            "no strings attached",
            "non-controlling",
            "noted",
            "novelty",
            "now",
            "obnoxious",
            "obsessed",
            "obsession",
            "obvious",
            "odd",
            "off-kilter",
            "off-limits",
            "off-the record",
            "offensive",
            "official",
            "okay",
            "on-demand",
            "open-minded",
            "opportunities",
            "optimistic",
            "ordeal",
            "outlawed",
            "outrageousness",
            "outstanding",
            "overcome",
            "overjoyed",
            "overnight",
            "overwhelmed",
            "packed",
            "painful",
            "painless",
            "painstaking",
            "pale",
            "panic",
            "panicked",
            "paralyzed",
            "pas",
            "passionate",
            "pathetic",
            "pay zero",
            "payback",
            "perfect",
            "peril",
            "perplexed",
            "perspective",
            "pessimistic",
            "pioneering",
            "piranha",
            "pitfall",
            "pitiful",
            "placid",
            "plague",
            "played",
            "playful",
            "pleased",
            "pluck",
            "plummet",
            "plunge",
            "poison",
            "poisonous",
            "polarizing",
            "poor",
            "popular",
            "portfolio",
            "pound",
            "powerful",
            "powerless",
            "practical",
            "preposterous",
            "prestige",
            "price",
            "priceless",
            "pride",
            "prison",
            "privacy",
            "private",
            "privileged",
            "prize",
            "problem",
            "productive",
            "professional",
            "profit",
            "profitable",
            "profound",
            "promiscuous",
            "promising",
            "promote",
            "protect",
            "protected",
            "proven",
            "provocative",
            "provoke",
            "psychological",
            "pummel",
            "punch",
            "punish",
            "pus",
            "quadruple",
            "quality",
            "quarrelsome",
            "quick",
            "quick-start",
            "quickly",
            "quiet",
            "radiant",
            "rare",
            "ravenous",
            "rebellious",
            "recession-proof",
            "reckoning",
            "recognized",
            "recommend",
            "recreate",
            "reduced",
            "reflective",
            "refugee",
            "refund",
            "refundable",
            "reject",
            "relaxed",
            "release",
            "relentless",
            "reliable",
            "remarkable",
            "replicate",
            "report",
            "reprimanding",
            "repulsed",
            "repulsive",
            "research",
            "resentful",
            "resourceful",
            "responsible",
            "responsive",
            "rested",
            "restricted",
            "results",
            "retaliating",
            "reveal",
            "revealing",
            "revenge",
            "revengeful",
            "revisited",
            "revolting",
            "revolutionary",
            "reward",
            "rich",
            "ridiculous",
            "risky",
            "riveting",
            "rookie",
            "rowdy",
            "ruin",
            "rules",
            "ruthless",
            "sabotaging",
            "sacred",
            "sadistic",
            "sadly",
            "sadness",
            "safe",
            "safety",
            "sale",
            "sampler",
            "sarcastic",
            "satisfied",
            "savage",
            "savagery",
            "save",
            "savings",
            "savvy",
            "scam",
            "scandal",
            "scandalous",
            "scarce",
            "scared",
            "scary",
            "scornful",
            "scream",
            "searing",
            "secret",
            "secret agenda",
            "secret plot",
            "secrets",
            "secure",
            "security",
            "seductive",
            "seething",
            "seize",
            "selected",
            "self-hating",
            "self-sufficient",
            "sensational",
            "senseless",
            "sensual",
            "serene",
            "seriously",
            "severe",
            "sex",
            "sexy",
            "shaking",
            "shameful",
            "shameless",
            "shaming",
            "shatter",
            "shellacking",
            "shocking",
            "should",
            "shrewd",
            "sick and tired",
            "signs",
            "silly",
            "simple",
            "simplicity",
            "simplified",
            "simplistic",
            "sincere",
            "sinful",
            "sins",
            "six-figure",
            "sizable",
            "sizzle",
            "sizzled",
            "sizzles",
            "sizzling",
            "sizzlingly",
            "skill",
            "skyrocket",
            "slaughter",
            "slave",
            "sleazy",
            "sleeping",
            "sly",
            "smash",
            "smiling",
            "smug",
            "smuggle",
            "smuggled",
            "sneak-peek",
            "sneaky",
            "sniveling",
            "snob",
            "snooty",
            "snotty",
            "soar",
            "soaring",
            "solid",
            "solution",
            "spank",
            "special",
            "spectacular",
            "speedy",
            "spell-binding",
            "spine",
            "spirit",
            "spirited",
            "spiteful",
            "spoiler",
            "spontaneous",
            "spotlight",
            "spunky",
            "squirming",
            "stable",
            "staggering",
            "startling",
            "steady",
            "steal",
            "stealthy",
            "steamy",
            "step-by-step",
            "still",
            "stoic",
            "stop",
            "strange",
            "strangle",
            "strategy",
            "stressed",
            "strong",
            "strongly suggest",
            "struggle",
            "stuck up",
            "studies",
            "stunning",
            "stupid",
            "stupid-simple",
            "sturdy",
            "sublime",
            "succeed",
            "success",
            "successful",
            "suck",
            "suddenly",
            "suffer",
            "sunny",
            "super",
            "super-human",
            "superb",
            "supercharge",
            "superior",
            "supported",
            "supportive",
            "sure",
            "sure fire",
            "surefire",
            "surge",
            "surging",
            "surprise",
            "surprised",
            "surprising",
            "survival",
            "survive",
            "suspicious",
            "sweaty",
            "swoon",
            "swoon-worthy",
            "tailspin",
            "tank",
            "tantalizing",
            "targeted",
            "tawdry",
            "tease",
            "technology",
            "teetering",
            "tempting",
            "tenacious",
            "tense",
            "terrible",
            "terrific",
            "terrified",
            "terrifying",
            "terror",
            "terrorist",
            "tested",
            "thankful",
            "the truth",
            "threaten",
            "threatened",
            "thrilled",
            "thrilling",
            "thug",
            "ticked off",
            "tickled",
            "timely",
            "today",
            "torture",
            "toxic",
            "track record",
            "trade secret",
            "tragedy",
            "tragic",
            "transform",
            "transparency",
            "trap",
            "trapped",
            "trauma",
            "traumatized",
            "treacherous",
            "treasure",
            "tremendous",
            "trend",
            "tricks",
            "triggers",
            "triple",
            "triumph",
            "truly",
            "trusting",
            "trustworthy",
            "truth",
            "truthful",
            "turbo-charge",
            "turbocharges",
            "tweaks",
            "twitching",
            "ultimate",
            "unadulterated",
            "unassuming",
            "unauthorized",
            "unbelievable",
            "unburdened",
            "uncaring",
            "uncensored",
            "uncertain",
            "uncomfortable",
            "unconditional",
            "uncontrollable",
            "unconventional",
            "uncovered",
            "undeniable",
            "under priced",
            "undercover",
            "underground",
            "underhanded",
            "underused",
            "unexpected",
            "unforgettable",
            "unheard of",
            "unhurried",
            "uninterested",
            "unique",
            "unjustified",
            "unknowingly",
            "unleashed",
            "unlimited",
            "unlock",
            "unparalleled",
            "unpopular",
            "unreliable",
            "unresponsive",
            "unseen",
            "unstable",
            "unstoppable",
            "unsure",
            "unsurpassed",
            "untapped",
            "unusual",
            "up-sell",
            "upbeat",
            "uplifted",
            "uplifting",
            "urge",
            "urgent",
            "useful",
            "useless",
            "validate",
            "valor",
            "valuable",
            "value",
            "vanquish",
            "vaporize",
            "venomous",
            "verify",
            "vibrant",
            "vicious",
            "victim",
            "victory",
            "vigorous",
            "vilified",
            "vindictive",
            "violated",
            "violent",
            "volatile",
            "vulnerable",
            "waiting",
            "wanted",
            "wanton",
            "warning",
            "waste",
            "weak",
            "wealth",
            "weird",
            "what no one tells you",
            "whip",
            "whopping",
            "wicked",
            "wild",
            "willpower",
            "withheld",
            "wonderful",
            "wondrous",
            "woozy",
            "world",
            "worry",
            "worst",
            "worthwhile",
            "wounded",
            "wreaking",
            "youthful",
            "zen",
            "zinger"
          ],
          "diacritics": true,
          "researchesTests": [
            "contentHasTOC",
            "contentHasShortParagraphs",
            "contentHasAssets",
            "keywordInTitle",
            "keywordInMetaDescription",
            "keywordInPermalink",
            "keywordIn10Percent",
            "keywordInContent",
            "keywordInSubheadings",
            "keywordInImageAlt",
            "keywordDensity",
            "keywordNotUsed",
            "lengthContent",
            "lengthPermalink",
            "linksHasInternal",
            "linksHasExternals",
            "linksNotAllExternals",
            "titleStartWithKeyword",
            "titleSentiment",
            "titleHasPowerWords",
            "titleHasNumber",
            "hasContentAI"
          ],
          "hasBreadcrumb": true,
          "serpData": {
            "title": "%sitename% %page% %sep% %sitedesc%",
            "description": "",
            "titleTemplate": "%sitename% %page% %sep% %sitedesc%",
            "descriptionTemplate": "",
            "focusKeywords": "",
            "breadcrumbTitle": "Home",
            "robots": {
              "index": true
            },
            "advancedRobots": [],
            "facebookTitle": "",
            "facebookDescription": "",
            "facebookImage": "",
            "facebookImageID": ""
          }
        }
      },
      "tocTitle": "Table of Contents",
      "tocExcludeHeadings": [],
      "listStyle": "ul"
    },
    "_links": {
      "self": [
        {
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/pages/12",
          "targetHints": {
            "allow": [
              "GET"
            ]
          }
        }
      ],
      "collection": [
        {
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/pages"
        }
      ],
      "about": [
        {
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/types/page"
        }
      ],
      "author": [
        {
          "embeddable": true,
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/users/1"
        }
      ],
      "replies": [
        {
          "embeddable": true,
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/comments?post=12"
        }
      ],
      "version-history": [
        {
          "count": 26,
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/pages/12/revisions"
        }
      ],
      "predecessor-version": [
        {
          "id": 635,
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/pages/12/revisions/635"
        }
      ],
      "wp:featuredmedia": [
        {
          "embeddable": true,
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/media/431"
        }
      ],
      "wp:attachment": [
        {
          "href": "https://loremwellnesscare.com/wp-json/wp/v2/media?parent=12"
        }
      ],
      "curies": [
        {
          "name": "wp",
          "href": "https://api.w.org/{rel}",
          "templated": true
        }
      ]
    }
  }
];

export const mockResponse = (type: string) => {
  switch (type) {
    case "common":
      return mockCommonContents;
    case "home":
      return mockHomeContents;
    default:
      return {};
  }
};